### ISSUE TITLE
I2C issue: Raspberry Pi 5 support

### ISSUE THREAD

**Issue by mehrdadfeller** [adafruit/Adafruit_CircuitPython_VEML7700#28]
I tried running the example in README but I get the error libgpiod Python bindings not found. I have latest version of the Blinka installed on my venv:

```
(.venv) ubo@raspberrypi:~ $ pip3 show adafruit-circuitpython-veml7700
Name: adafruit-circuitpython-veml7700
Version: 1.1.21
Summary: CircuitPython driver for VEML7700 high precision I2C ambient light sensor.
Home-page: 
Author: 
Author-email: Adafruit Industries <circuitpython@adafruit.com>
License: MIT
Location: /home/ubo/.venv/lib/python3.11/site-packages
Requires: Adafruit-Blinka, adafruit-circuitpython-busdevice, adafruit-circuitpython-register
Required-by: 
```

Package info for Blinka:

```
 pip3 show Adafruit-Blinka
Name: Adafruit-Blinka
Version: 8.26.0
Summary: CircuitPython APIs for non-CircuitPython versions of Python such as CPython on Linux and MicroPython.
Home-page: https://github.com/adafruit/Adafruit_Blinka
Author: Adafruit Industries
Author-email: circuitpython@adafruit.com
License: MIT
Location: /home/ubo/.venv/lib/python3.11/site-packages
Requires: adafruit-circuitpython-typing, Adafruit-PlatformDetect, Adafruit-PureIO, pyftdi, rpi-ws281x, RPi.GPIO, sysv-ipc
Required-by: adafruit-circuitpython-busdevice, adafruit-circuitpython-register, adafruit-circuitpython-requests, adafruit-circuitpython-typing, adafruit-circuitpython-veml7700
```

Here's the error log trace:

```
ImportError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubo/lightsensor.py", line 2, in <module>
    import board
  File "/home/ubo/.venv/lib/python3.11/site-packages/board.py", line 47, in <module>
    from adafruit_blinka.board.raspberrypi.raspi_5b import *
  File "/home/ubo/.venv/lib/python3.11/site-packages/adafruit_blinka/board/raspberrypi/raspi_5b.py", line 6, in <module>
    from adafruit_blinka.microcontroller.bcm2712 import pin
  File "/home/ubo/.venv/lib/python3.11/site-packages/adafruit_blinka/microcontroller/bcm2712/pin.py", line 5, in <module>
    from adafruit_blinka.microcontroller.generic_linux.libgpiod_pin import Pin
  File "/home/ubo/.venv/lib/python3.11/site-packages/adafruit_blinka/microcontroller/generic_linux/libgpiod_pin.py", line 8, in <module>
    raise ImportError(
ImportError: libgpiod Python bindings not found, please install and try again! See https://github.com/adafruit/Raspberry-Pi-Installer-Scripts/blob/master/libgpiod.sh
```

Please let me know if I can investigate something further. BTW, the script mentioned in the error does not exist:

`https://github.com/adafruit/Raspberry-Pi-Installer-Scripts/blob/master/libgpiod.sh`

**Comment by mehrdadfeller** [comment]
I think the link in the error is referring to `libgpio.py` not `libgpio.sh`. Anyways, running `sudo python3 libgpio.py` throws a bunch of errors too:

```
LIBGPIOD make[3]: Entering directory '/tmp/libgpiod.ArQq/bindings/python'
LIBGPIOD Making all in gpiod
LIBGPIOD make[4]: Entering directory '/tmp/libgpiod.ArQq/bindings/python/gpiod'
LIBGPIOD Making all in ext
LIBGPIOD make[5]: Entering directory '/tmp/libgpiod.ArQq/bindings/python/gpiod/ext'
make[5]: Nothing to be done for 'all'.
make[5]: Leaving directory '/tmp/libgpiod.ArQq/bindings/python/gpiod/ext'
LIBGPIOD make[5]: Entering directory '/tmp/libgpiod.ArQq/bindings/python/gpiod'
make[5]: Nothing to be done for 'all-am'.
LIBGPIOD make[5]: Leaving directory '/tmp/libgpiod.ArQq/bindings/python/gpiod'
LIBGPIOD make[4]: Leaving directory '/tmp/libgpiod.ArQq/bindings/python/gpiod'
LIBGPIOD make[4]: Entering directory '/tmp/libgpiod.ArQq/bindings/python'
CFLAGS="-I/tmp/libgpiod.ArQq/include/ -I/tmp/libgpiod.ArQq/tests/gpiosim \
-L/tmp/libgpiod.ArQq/lib/.libs/ -L/tmp/libgpiod.ArQq/tests/gpiosim/.libs/" \
/usr/bin/python -m build
LIBGPIOD /usr/bin/python: No module named build
LIBGPIOD make[4]: *** [Makefile:689: all-local] Error 1
LIBGPIOD make[4]: Leaving directory '/tmp/libgpiod.ArQq/bindings/python'
LIBGPIOD make[3]: *** [Makefile:401: all-recursive] Error 1
LIBGPIOD make[3]: Leaving directory '/tmp/libgpiod.ArQq/bindings/python'
LIBGPIOD make[2]: *** [Makefile:398: all-recursive] Error 1
LIBGPIOD make[2]: Leaving directory '/tmp/libgpiod.ArQq/bindings'
LIBGPIOD make[1]: *** [Makefile:467: all-recursive] Error 1
LIBGPIOD make[1]: Leaving directory '/tmp/libgpiod.ArQq'
LIBGPIOD make: *** [Makefile:397: all] Error 2
```

**Comment by mehrdadfeller** [comment]
I managed to fix the issue:

The problem I was facing had to do with trying to install `adafruit-circuitpython-veml7700` in virtual environment but it seems like currently `gpio` python package can only be installed with sudo system wide. 

For that reason, `--system-site-packages` would be necessary when installing the virtual environment.

I also had to manually install build module system wide as it is not installed by default:

`sudo pip3 install build`

**Comment by mehrdadfeller** [comment]
By the way, it looks like there is a change in recommended way of installing system wide packages using `apt install python3-xyz`

Incidentally I bumped into this package but I have not tested it yet:
https://github.com/hhk7734/python3-gpiod


This is the warning that is being shown if you run `sudo pip install` and it aborts if you do not include the `--break-system-packages` flag -- which does not feel right. 

```
ubo@raspberrypi:~ $ sudo pip3 install adafruit-circuitpython-veml7700
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    For more information visit http://rptl.io/venv

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
```
